//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.19 at 12:21:34 PM GMT 
//


package in.gov.uidai.authentication.uid_auth_response._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the in.gov.uidai.authentication.uid_auth_response._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AuthRes_QNAME = new QName("http://www.uidai.gov.in/authentication/uid-auth-response/1.0", "AuthRes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: in.gov.uidai.authentication.uid_auth_response._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthRes }
     * 
     */
    public AuthRes createAuthRes() {
        return new AuthRes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthRes }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AuthRes }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.uidai.gov.in/authentication/uid-auth-response/1.0", name = "AuthRes")
    public JAXBElement<AuthRes> createAuthRes(AuthRes value) {
        return new JAXBElement<AuthRes>(_AuthRes_QNAME, AuthRes.class, null, value);
    }

}
