//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.19 at 12:21:34 PM GMT 
//


package in.gov.uidai.authentication.common.types._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuthErrorClassification.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AuthErrorClassification"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UID_NOT_FOUND"/&gt;
 *     &lt;enumeration value="UID_INACTIVE"/&gt;
 *     &lt;enumeration value="UID_BLOCKED"/&gt;
 *     &lt;enumeration value="INCORRECT_PIN"/&gt;
 *     &lt;enumeration value="INCORRECT_OTP"/&gt;
 *     &lt;enumeration value="TKN_MISMATCH"/&gt;
 *     &lt;enumeration value="FRAUD_CHECK_FAILED"/&gt;
 *     &lt;enumeration value="NO_BIOMETRIC_GALLERY"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AuthErrorClassification", namespace = "http://www.uidai.gov.in/authentication/common/types/1.0")
@XmlEnum
public enum AuthErrorClassification {

    UID_NOT_FOUND,
    UID_INACTIVE,
    UID_BLOCKED,
    INCORRECT_PIN,
    INCORRECT_OTP,
    TKN_MISMATCH,
    FRAUD_CHECK_FAILED,
    NO_BIOMETRIC_GALLERY;

    public String value() {
        return name();
    }

    public static AuthErrorClassification fromValue(String v) {
        return valueOf(v);
    }

}
