//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.19 at 12:21:34 PM GMT 
//


package in.gov.uidai.authentication.uid_auth_request_data._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Base 64 encoded biometric record
 *                
 * 
 * <p>Java class for Bio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bio"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;base64Binary"&gt;
 *       &lt;attribute name="type" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}bioMetricType" /&gt;
 *       &lt;attribute name="pos" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}BiometricPosition" default="UNKNOWN" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bio", propOrder = {
    "value"
})
public class Bio {

    @XmlValue
    protected byte[] value;
    @XmlAttribute(name = "type")
    protected BioMetricType type;
    @XmlAttribute(name = "pos")
    protected BiometricPosition pos;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setValue(byte[] value) {
        this.value = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link BioMetricType }
     *     
     */
    public BioMetricType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link BioMetricType }
     *     
     */
    public void setType(BioMetricType value) {
        this.type = value;
    }

    /**
     * Gets the value of the pos property.
     * 
     * @return
     *     possible object is
     *     {@link BiometricPosition }
     *     
     */
    public BiometricPosition getPos() {
        if (pos == null) {
            return BiometricPosition.UNKNOWN;
        } else {
            return pos;
        }
    }

    /**
     * Sets the value of the pos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BiometricPosition }
     *     
     */
    public void setPos(BiometricPosition value) {
        this.pos = value;
    }

}
