//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.19 at 12:21:34 PM GMT 
//


package in.gov.uidai.authentication.uid_auth_request_data._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Meta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Meta"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Locn" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Locn" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="fdc" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Code" /&gt;
 *       &lt;attribute name="idc" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Code" /&gt;
 *       &lt;attribute name="apc" use="required" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Code" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Meta", propOrder = {
    "locn"
})
public class Meta {

    @XmlElement(name = "Locn")
    protected Locn locn;
    @XmlAttribute(name = "fdc")
    protected String fdc;
    @XmlAttribute(name = "idc")
    protected String idc;
    @XmlAttribute(name = "apc", required = true)
    protected String apc;

    /**
     * Gets the value of the locn property.
     * 
     * @return
     *     possible object is
     *     {@link Locn }
     *     
     */
    public Locn getLocn() {
        return locn;
    }

    /**
     * Sets the value of the locn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Locn }
     *     
     */
    public void setLocn(Locn value) {
        this.locn = value;
    }

    /**
     * Gets the value of the fdc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFdc() {
        return fdc;
    }

    /**
     * Sets the value of the fdc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFdc(String value) {
        this.fdc = value;
    }

    /**
     * Gets the value of the idc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdc() {
        return idc;
    }

    /**
     * Sets the value of the idc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdc(String value) {
        this.idc = value;
    }

    /**
     * Gets the value of the apc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApc() {
        return apc;
    }

    /**
     * Sets the value of the apc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApc(String value) {
        this.apc = value;
    }

}
